select reportdate ,
source_uri  ,
position  ,
isrc ,
track_uri ,
regexp_replace(track, '\\t', ' ')  as track,
regexp_replace(justtrack, '\\t', ' ') as justtrack,
streams ,
skips ,
length  ,
disc  ,
col ,
ret ,
sup ,
httype  ,
baseline  ,
skipsperc ,
skipsperf ,
lengthperf  ,
discperf  ,
colperf ,
retperf ,
supperf ,
skipsb4 ,
skipsb4perf ,
skipsperfbench  ,
colperfbench  ,
usercluster ,
clustername ,
regexp_replace(playlist_name, '\\t', ' ') as playlist_name,
releaseyear ,
releasetype ,
regexp_replace(PMainType, '\\t', ' ')  as PMainType,
regexp_replace(PMinorType, '\\t', ' ') as PMinorType,
regexp_replace(PSubType, '\\t', ' ')  as PSubType,
regexp_replace(owner, '\\t', ' ') as owner ,
regexp_replace(artist, '\\t', ' ') as artist,
DiscoveryType ,
PerfCode  ,
PerfType  ,
score ,
playlists ,
hottrack  ,
hottrackscore
from `umg-comm-tech-dev.optimize_qa.AR_APOLLO_DATA_load_comp`
